### ISSUE TITLE
pet sync failed

### ISSUE THREAD

**Issue by xingheng** [knqyf263/pet#133]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1418a7b]

goroutine 1 [running]:
github.com/knqyf263/pet/sync.GistClient.GetSnippet(0xc000142480, 0xc0001440c0, 0x20, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/knqyf263/pet/sync/gist.go:64 +0x49b
github.com/knqyf263/pet/sync.AutoSync(0xc000144030, 0x26, 0x0, 0x0)
	/home/travis/gopath/src/github.com/knqyf263/pet/sync/sync.go:33 +0x67
github.com/knqyf263/pet/cmd.sync(0x1a3c400, 0x1a5f270, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/knqyf263/pet/cmd/sync.go:18 +0x39
github.com/knqyf263/pet/vendor/github.com/spf13/cobra.(*Command).execute(0x1a3c400, 0x1a5f270, 0x0, 0x0, 0x1a3c400, 0x1a5f270)
	/home/travis/gopath/src/github.com/knqyf263/pet/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/knqyf263/pet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1a3d240, 0xc0000edf68, 0x146854e, 0x1a3d240)
	/home/travis/gopath/src/github.com/knqyf263/pet/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/knqyf263/pet/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/src/github.com/knqyf263/pet/vendor/github.com/spf13/cobra/command.go:800
github.com/knqyf263/pet/cmd.Execute()
	/home/travis/gopath/src/github.com/knqyf263/pet/cmd/root.go:48 +0x32
main.main()
	/home/travis/gopath/src/github.com/knqyf263/pet/main.go:20 +0x20
```

Go version: `go version go1.10.3 darwin/amd64`

**Comment by hariprasadraja** [comment]
May be you can update your go version and give a try.  for **go1.15+**  It is working fine

**Comment by xingheng** [comment]
Reinstalled `pet` resolved it.
