### ISSUE TITLE
brew fails

### ISSUE THREAD

**Issue by 9mm** [knqyf263/pet#220]
It seems everything in brew fails now

```
Error: Invalid formula (arm64_ventura): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
Error: Invalid formula (arm64_monterey): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
Error: Invalid formula (arm64_big_sur): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
Error: Invalid formula (ventura): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
Error: Invalid formula (monterey): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
Error: Invalid formula (big_sur): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
Error: Invalid formula (catalina): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
Error: Invalid formula (mojave): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
Error: Invalid formula (high_sierra): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
Error: Invalid formula (sierra): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
Error: Invalid formula (el_capitan): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
Error: Invalid formula (x86_64_linux): /opt/homebrew/Library/Taps/knqyf263/homebrew-pet/pet.rb
formulae require at least a URL
```

**Comment by 9mm** [comment]
```
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/formula.rb:285:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:216:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:404:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:404:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:565:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:711:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:684:in `from_rack'
/opt/homebrew/Library/Homebrew/diagnostic.rb:717:in `block in check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `each'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:60:in `block in doctor'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `each'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `doctor'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by knqyf263** [comment]
Thanks. I'm on it.

**Comment by 9mm** [comment]
Awesome, thanks! Glad to see some interest still in this, I've had this installed since the beginning and its amazing, I have like 100+ snippets

**Comment by knqyf263** [comment]
It should have been fixed.

>I've had this installed since the beginning and its amazing, I have like 100+ snippets

Thanks for using my tool! I hope to add more features (snippet repository, etc) if time permits.

**Comment by 9mm** [comment]
works now! thanks again

**Comment by knqyf263** [comment]
You may need to clear the cache. I wanted to fix the issue as soon as possible, so I simply removed the directory.

```rm -rf /opt/homebrew/Library/Taps/knqyf263/homebrew-pet```
