### ISSUE TITLE
panic: runtime error SIGSEGV during sync command

### ISSUE THREAD

**Issue by kenetik** [knqyf263/pet#9]
```
$ pet --debug sync
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x136cb94]

goroutine 1 [running]:
github.com/knqyf263/pet/cmd.download(0x145bdc7, 0xb)
	/Users/teppei/src/github.com/knqyf263/pet/cmd/sync.go:101 +0x1c4
github.com/knqyf263/pet/cmd.sync(0x165f160, 0xc4200153c0, 0x0, 0x1, 0x0, 0x0)
	/Users/teppei/src/github.com/knqyf263/pet/cmd/sync.go:34 +0x5f
github.com/spf13/cobra.(*Command).execute(0x165f160, 0xc420015350, 0x1, 0x1, 0x165f160, 0xc420015350)
	/Users/teppei/src/github.com/spf13/cobra/command.go:644 +0x3ef
github.com/spf13/cobra.(*Command).ExecuteC(0x165eb00, 0xc42001e0b8, 0x0, 0x1661c28)
	/Users/teppei/src/github.com/spf13/cobra/command.go:734 +0x339
github.com/spf13/cobra.(*Command).Execute(0x165eb00, 0x1, 0x0)
	/Users/teppei/src/github.com/spf13/cobra/command.go:693 +0x2b
github.com/knqyf263/pet/cmd.Execute()
	/Users/teppei/src/github.com/knqyf263/pet/cmd/root.go:47 +0x31
main.main()
	/Users/teppei/src/github.com/knqyf263/pet/main.go:20 +0x20
```

**Comment by knqyf263** [comment]
@kenetik Thanks for your report!
Could you tell me the OS you are using?
And, I'd like to see your config file (you can see `pet configure`).

**Comment by knqyf263** [comment]
I think that this problem was fixed (thanks @b4b4r07 ).
If you still have a problem,  please reopen!
